[package]
license = "MIT OR Apache-2.0"
name = "bloodhound-opengraph"
version = "0.1.1"
edition = "2024"
description = "BloodHound OpenGraph JSON builder and schema structures"
repository = "https://github.com/JVBotelho/ghosthound"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
